#! /bin/sh
### BEGIN INIT INFO
# Provides:         ipc_mserver
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init_script for ipc_mserver connection
# Description:       the init_script, which handles the ipc-mserver-module
### END INIT INFO
# Author: Daniel Belles <daniel.belles@web.de>

# Aktionen
case "$1" in
    start)
        /home/l31n/source/beagleboard/bin/ipc_mserver start
        ;;
    stop)
        /home/l31n/source/beagleboard/bin/ipc_mserver stop
        ;;
    restart)
        /home/l31n/source/beagleboard/bin/ipc_mserver restart
        ;;
esac

exit 0
