#!/bin/bash

if [ $# -eq 0 ]
then
	echo "Usage: $0 [cbp-file] [target = Release]"
	exit 1
fi 

/usr/bin/cbp2mak $1 makefile

if [ $# -eq 1 ]
then
	make Release
elif [ $# -eq 2 ]
then
	make $2
else
	echo "Usage: $0 [cbp-file] [target = Release]"
fi

rm makefile
